// Reference content in Portuguese. Rows and display order follow the English
// file; see reference_text.dart.
import 'reference_text.dart';

/// Portuguese reference content.
const ReferenceText referenceTextPt = ReferenceText(
  qCodes: <String, String>{
    'QRL': 'A frequência está ocupada? / A frequência está ocupada.',
    'QRM': 'Interferência de outras estações (artificial).',
    'QRN': 'Estática / ruído atmosférico.',
    'QRO': 'Aumente a potência / alta potência.',
    'QRP': 'Reduza a potência / baixa potência (5 W ou menos).',
    'QRQ': 'Transmita mais rápido.',
    'QRS': 'Transmita mais devagar.',
    'QRT': 'Pare de transmitir / estou encerrando.',
    'QRU': 'Tem algo para mim? / Não tenho nada para você.',
    'QRV': 'Está pronto? / Estou pronto.',
    'QRX': 'Aguarde; chamarei você novamente às (hora).',
    'QRZ': 'Quem está me chamando?',
    'QSB': 'Seu sinal está com desvanecimento.',
    'QSL': 'Pode confirmar o recebimento? / Confirmo o recebimento.',
    'QSO': 'Um comunicado; posso me comunicar com (estação).',
    'QSY': 'Mude para outra frequência.',
    'QTH': 'Qual é a sua localização? / Minha localização é (local).',
    'QRA': 'O nome da minha estação é (indicativo).',
    'QRG': 'Sua frequência exata é (kHz).',
    'QRH': 'Sua frequência está variando.',
    'QRI': 'O tom da sua transmissão é (bom / variável / ruim).',
    'QRK': 'A inteligibilidade do seu sinal é (1 a 5).',
    'QSA': 'A intensidade do seu sinal é (1 a 5).',
    'QSK': 'Ouço você entre meus sinais; pode interromper minha transmissão.',
    'QSP': 'Pode retransmitir para (estação)? / Vou retransmitir.',
    'QST': 'Chamada geral a todas as estações de radioamador.',
    'QSV': 'Transmita uma série de V para sintonia.',
    'QSZ': 'Transmita cada palavra ou grupo duas vezes.',
    'QTC': 'Tenho (número) mensagens para você.',
    'QTR': 'Qual é a hora certa? / A hora certa é (UTC).',
  },
  abbreviations: <String, String>{
    'CQ': 'Chamada geral a qualquer estação.',
    'DE': 'De (antecede o indicativo de quem transmite).',
    'K': 'Câmbio, qualquer estação.',
    'KN': 'Câmbio, somente a estação chamada.',
    '73': 'Cordiais saudações.',
    '88': 'Beijos e abraços.',
    'TU': 'Obrigado.',
    'AGN': 'Novamente.',
    'ANT': 'Antena.',
    'BK': 'Interrupção; devolvo a palavra a você (câmbio rápido).',
    'BTU': 'Devolvo a palavra a você.',
    'CUL': 'Até mais.',
    'ES': 'E.',
    'FB': 'Excelente (fine business).',
    'GA': 'Boa tarde.',
    'GE': 'Boa noite (cumprimento).',
    'GM': 'Bom dia.',
    'HR': 'Aqui.',
    'HW': 'Como está me copiando?',
    'NR': 'Número.',
    'OM': 'Old man (qualquer operador do sexo masculino).',
    'PSE': 'Por favor.',
    'PWR': 'Potência.',
    'R': 'Recebido / entendido.',
    'RIG': 'Equipamento da estação.',
    'RST': 'Reporte de sinal: inteligibilidade, intensidade, tom.',
    'SRI': 'Desculpe.',
    'TNX': 'Obrigado.',
    'UR': 'Seu / você é.',
    'WX': 'Tempo (meteorologia).',
    'XYL': 'Esposa (ex-young lady).',
    'YL': 'Young lady (operadora).',
    'ABT': 'Sobre / aproximadamente.',
    'ADR': 'Endereço.',
    'B4': 'Antes.',
    'C': 'Sim / correto.',
    'CFM': 'Confirmo.',
    'CPI': 'Copio.',
    'CUD': 'Poderia (could).',
    'DX': 'Estação distante.',
    'GB': 'Adeus.',
    'GN': 'Boa noite (despedida).',
    'GND': 'Terra (aterramento).',
    'GUD': 'Bom.',
    'HI': 'Risada.',
    'HPE': 'Espero.',
    'NW': 'Agora.',
    'OP': 'Operador.',
    'RPT': 'Repita.',
    'SIG': 'Sinal.',
    'TKS': 'Obrigado.',
    'TMW': 'Amanhã.',
    'VY': 'Muito.',
    'WKD': 'Trabalhado (comunicado realizado).',
    'WUD':
        'Auxiliar inglês usado para indicar condição ou fazer pedidos corteses (would).',
    '55': 'Boa sorte.',
  },
  prosigns: <String, String>{
    'AR': 'Fim da mensagem.',
    'SK': 'Fim do comunicado.',
    'BT': 'Separação / novo parágrafo.',
    'KN': 'Câmbio, somente a estação chamada.',
    'AS': 'Aguarde / um momento.',
    'SN': 'Entendido.',
    'SOS': 'Socorro.',
    'CT': 'Início da transmissão (atenção).',
    'HH': 'Erro; a última palavra será repetida.',
  },
  punctuation: <String, String>{
    '.': 'Ponto final',
    ',': 'Vírgula',
    '?': 'Ponto de interrogação',
    '\'': 'Apóstrofo',
    '!': 'Ponto de exclamação',
    '/': 'Barra (traço de fração)',
    '(': 'Abre parênteses',
    ')': 'Fecha parênteses',
    '&': 'E comercial (aguarde)',
    ':': 'Dois-pontos',
    ';': 'Ponto e vírgula',
    '=': 'Igual (separação, BT)',
    '+': 'Mais (fim da mensagem, AR)',
    '-': 'Hífen / menos',
    '_': 'Sublinhado',
    '"': 'Aspas',
    '\$': 'Cifrão',
    '@': 'Arroba',
  },
  digitPhrases: <String, String>{
    '1': 'um ponto, depois quatro traços',
    '2': 'dois pontos, depois três traços',
    '3': 'três pontos, depois dois traços',
    '4': 'quatro pontos, depois um traço',
    '5': 'cinco pontos',
    '6': 'um traço, depois quatro pontos',
    '7': 'dois traços, depois três pontos',
    '8': 'três traços, depois dois pontos',
    '9': 'quatro traços, depois um ponto',
    '0': 'cinco traços',
  },
  phraseNote: ' (frase mnemônica em inglês; as sílabas tônicas são traços)',
);
