// Reference content in English. Rows and display order follow the English
// file; see reference_text.dart.
import 'reference_text.dart';

/// English reference content.
const ReferenceText referenceTextEn = ReferenceText(
  qCodes: <String, String>{
    'QRL': 'Is the frequency in use? / The frequency is in use.',
    'QRM': 'Interference from other stations (man-made).',
    'QRN': 'Static / atmospheric noise.',
    'QRO': 'Increase power / high power.',
    'QRP': 'Reduce power / low power (5 W or less).',
    'QRQ': 'Send faster.',
    'QRS': 'Send more slowly.',
    'QRT': 'Stop sending / I am closing down.',
    'QRU': 'Have you anything for me? / I have nothing for you.',
    'QRV': 'Are you ready? / I am ready.',
    'QRX': 'Stand by; I will call you again at (time).',
    'QRZ': 'Who is calling me?',
    'QSB': 'Your signal is fading.',
    'QSL': 'Can you acknowledge? / I acknowledge receipt.',
    'QSO': 'A contact; I can communicate with (station).',
    'QSY': 'Change to another frequency.',
    'QTH': 'What is your location? / My location is (place).',
    'QRA': 'The name of my station is (call).',
    'QRG': 'Your exact frequency is (kHz).',
    'QRH': 'Your frequency varies.',
    'QRI': 'The tone of your transmission is (good / variable / bad).',
    'QRK': 'The readability of your signal is (1 to 5).',
    'QSA': 'The strength of your signal is (1 to 5).',
    'QSK': 'I can hear you between my signals; break in on my transmission.',
    'QSP': 'Will you relay to (station)? / I will relay.',
    'QST': 'General call to all amateur stations.',
    'QSV': 'Send a series of Vs for tuning.',
    'QSZ': 'Send each word or group twice.',
    'QTC': 'I have (number) messages for you.',
    'QTR': 'What is the correct time? / The correct time is (UTC).',
  },
  abbreviations: <String, String>{
    'CQ': 'Calling any station.',
    'DE': 'From (precedes the sender\'s call sign).',
    'K': 'Go ahead, any station.',
    'KN': 'Go ahead, named station only.',
    '73': 'Best regards.',
    '88': 'Love and kisses.',
    'TU': 'Thank you.',
    'AGN': 'Again.',
    'ANT': 'Antenna.',
    'BK': 'Break; back to you (quick turnover).',
    'BTU': 'Back to you.',
    'CUL': 'See you later.',
    'ES': 'And.',
    'FB': 'Fine business (excellent).',
    'GA': 'Good afternoon.',
    'GE': 'Good evening.',
    'GM': 'Good morning.',
    'HR': 'Here.',
    'HW': 'How do you copy?',
    'NR': 'Number.',
    'OM': 'Old man (any male operator).',
    'PSE': 'Please.',
    'PWR': 'Power.',
    'R': 'Roger / received.',
    'RIG': 'Station equipment.',
    'RST': 'Signal report: readability, strength, tone.',
    'SRI': 'Sorry.',
    'TNX': 'Thanks.',
    'UR': 'Your / you are.',
    'WX': 'Weather.',
    'XYL': 'Wife (ex-young lady).',
    'YL': 'Young lady (female operator).',
    'ABT': 'About.',
    'ADR': 'Address.',
    'B4': 'Before.',
    'C': 'Yes / correct.',
    'CFM': 'Confirm.',
    'CPI': 'Copy.',
    'CUD': 'Could.',
    'DX': 'Distant station.',
    'GB': 'Goodbye.',
    'GN': 'Good night.',
    'GND': 'Ground.',
    'GUD': 'Good.',
    'HI': 'Laughter.',
    'HPE': 'Hope.',
    'NW': 'Now.',
    'OP': 'Operator.',
    'RPT': 'Repeat.',
    'SIG': 'Signal.',
    'TKS': 'Thanks.',
    'TMW': 'Tomorrow.',
    'VY': 'Very.',
    'WKD': 'Worked.',
    'WUD': 'Would.',
    '55': 'Good luck.',
  },
  prosigns: <String, String>{
    'AR': 'End of message.',
    'SK': 'End of contact.',
    'BT': 'Break / new paragraph.',
    'KN': 'Go ahead, named station only.',
    'AS': 'Wait / stand by.',
    'SN': 'Understood.',
    'SOS': 'Distress.',
    'CT': 'Start of transmission (attention).',
    'HH': 'Error; the last word will be repeated.',
  },
  punctuation: <String, String>{
    '.': 'Period (full stop)',
    ',': 'Comma',
    '?': 'Question mark',
    '\'': 'Apostrophe',
    '!': 'Exclamation mark',
    '/': 'Slash (fraction bar)',
    '(': 'Open parenthesis',
    ')': 'Close parenthesis',
    '&': 'Ampersand (wait)',
    ':': 'Colon',
    ';': 'Semicolon',
    '=': 'Equals (break, BT)',
    '+': 'Plus (end of message, AR)',
    '-': 'Hyphen / minus',
    '_': 'Underscore',
    '"': 'Quotation mark',
    '\$': 'Dollar sign',
    '@': 'At sign',
  },
);
