// Reference content in Spanish. Rows and display order follow the English
// file; see reference_text.dart.
import 'reference_text.dart';

/// Spanish reference content.
const ReferenceText referenceTextEs = ReferenceText(
  qCodes: <String, String>{
    'QRL': '¿Está ocupada la frecuencia? / La frecuencia está ocupada.',
    'QRM': 'Interferencias de otras estaciones (artificiales).',
    'QRN': 'Estática / ruido atmosférico.',
    'QRO': 'Aumenta la potencia / potencia alta.',
    'QRP': 'Reduce la potencia / baja potencia (5 W o menos).',
    'QRQ': 'Transmite más rápido.',
    'QRS': 'Transmite más despacio.',
    'QRT': 'Deja de transmitir / cierro la estación.',
    'QRU': '¿Tienes algo para mí? / No tengo nada para ti.',
    'QRV': '¿Estás listo? / Estoy listo.',
    'QRX': 'Espera; te llamaré de nuevo a las (hora).',
    'QRZ': '¿Quién me llama?',
    'QSB': 'Tu señal tiene desvanecimiento.',
    'QSL': '¿Puedes acusar recibo? / Acuso recibo.',
    'QSO': 'Un comunicado; puedo comunicar con (estación).',
    'QSY': 'Pasa a otra frecuencia.',
    'QTH': '¿Cuál es tu ubicación? / Mi ubicación es (lugar).',
    'QRA': 'El nombre de mi estación es (indicativo).',
    'QRG': 'Tu frecuencia exacta es (kHz).',
    'QRH': 'Tu frecuencia varía.',
    'QRI': 'El tono de tu transmisión es (bueno / variable / malo).',
    'QRK': 'La inteligibilidad de tu señal es (1 a 5).',
    'QSA': 'La intensidad de tu señal es (1 a 5).',
    'QSK': 'Te oigo entre mis señales; puedes interrumpir mi transmisión.',
    'QSP': '¿Puedes retransmitir a (estación)? / Retransmitiré.',
    'QST': 'Llamada general a todas las estaciones de aficionado.',
    'QSV': 'Transmite una serie de V para sintonizar.',
    'QSZ': 'Transmite cada palabra o grupo dos veces.',
    'QTC': 'Tengo (número) mensajes para ti.',
    'QTR': '¿Cuál es la hora exacta? / La hora exacta es (UTC).',
  },
  abbreviations: <String, String>{
    'CQ': 'Llamada general a cualquier estación.',
    'DE': 'De (precede al indicativo de quien transmite).',
    'K': 'Adelante, cualquier estación.',
    'KN': 'Adelante, solo la estación llamada.',
    '73': 'Saludos cordiales.',
    '88': 'Besos y abrazos.',
    'TU': 'Gracias.',
    'AGN': 'Otra vez.',
    'ANT': 'Antena.',
    'BK': 'Break; te devuelvo el cambio (cambio rápido).',
    'BTU': 'Te devuelvo el cambio.',
    'CUL': 'Hasta luego.',
    'ES': 'Y.',
    'FB': 'Excelente (fine business).',
    'GA': 'Buenas tardes.',
    'GE': 'Buenas noches (saludo).',
    'GM': 'Buenos días.',
    'HR': 'Aquí.',
    'HW': '¿Cómo me copias?',
    'NR': 'Número.',
    'OM': 'Old man (cualquier operador masculino).',
    'PSE': 'Por favor.',
    'PWR': 'Potencia.',
    'R': 'Recibido / entendido.',
    'RIG': 'Equipo de la estación.',
    'RST': 'Reporte de señal: inteligibilidad, intensidad, tono.',
    'SRI': 'Lo siento.',
    'TNX': 'Gracias.',
    'UR': 'Tu / eres.',
    'WX': 'Tiempo (meteorología).',
    'XYL': 'Esposa (ex-young lady).',
    'YL': 'Young lady (operadora).',
    'ABT': 'Acerca de / aproximadamente.',
    'ADR': 'Dirección.',
    'B4': 'Antes.',
    'C': 'Sí / correcto.',
    'CFM': 'Confirmo.',
    'CPI': 'Copio.',
    'CUD': 'Podría (could).',
    'DX': 'Estación lejana.',
    'GB': 'Adiós.',
    'GN': 'Buenas noches (despedida).',
    'GND': 'Tierra.',
    'GUD': 'Bueno.',
    'HI': 'Risa.',
    'HPE': 'Espero.',
    'NW': 'Ahora.',
    'OP': 'Operador.',
    'RPT': 'Repite.',
    'SIG': 'Señal.',
    'TKS': 'Gracias.',
    'TMW': 'Mañana.',
    'VY': 'Muy.',
    'WKD': 'Trabajado (comunicado realizado).',
    'WUD': 'Auxiliar inglés del condicional (would).',
    '55': 'Buena suerte.',
  },
  prosigns: <String, String>{
    'AR': 'Fin del mensaje.',
    'SK': 'Fin del comunicado.',
    'BT': 'Separación / nuevo párrafo.',
    'KN': 'Adelante, solo la estación llamada.',
    'AS': 'Espera / un momento.',
    'SN': 'Entendido.',
    'SOS': 'Socorro.',
    'CT': 'Inicio de la transmisión (atención).',
    'HH': 'Error; se repetirá la última palabra.',
  },
  punctuation: <String, String>{
    '.': 'Punto',
    ',': 'Coma',
    '?': 'Signo de interrogación',
    '\'': 'Apóstrofo',
    '!': 'Signo de exclamación',
    '/': 'Barra (barra de fracción)',
    '(': 'Abrir paréntesis',
    ')': 'Cerrar paréntesis',
    '&': 'Et (espera)',
    ':': 'Dos puntos',
    ';': 'Punto y coma',
    '=': 'Igual (separación, BT)',
    '+': 'Más (fin del mensaje, AR)',
    '-': 'Guion / menos',
    '_': 'Guion bajo',
    '"': 'Comillas',
    '\$': 'Signo de dólar',
    '@': 'Arroba',
  },
  digitPhrases: <String, String>{
    '1': 'un punto, luego cuatro rayas',
    '2': 'dos puntos, luego tres rayas',
    '3': 'tres puntos, luego dos rayas',
    '4': 'cuatro puntos, luego una raya',
    '5': 'cinco puntos',
    '6': 'una raya, luego cuatro puntos',
    '7': 'dos rayas, luego tres puntos',
    '8': 'tres rayas, luego dos puntos',
    '9': 'cuatro rayas, luego un punto',
    '0': 'cinco rayas',
  },
  phraseNote: ' (frase mnemotécnica en inglés; las sílabas tónicas son rayas)',
);
