// Reference content in French. Rows and display order follow the English
// file; see reference_text.dart.
import 'reference_text.dart';

/// French reference content.
const ReferenceText referenceTextFr = ReferenceText(
  qCodes: <String, String>{
    'QRL': 'La fréquence est-elle occupée ? / La fréquence est occupée.',
    'QRM': 'Brouillage par d’autres stations (parasites artificiels).',
    'QRN': 'Parasites atmosphériques.',
    'QRO': 'Augmentez la puissance / forte puissance.',
    'QRP': 'Réduisez la puissance / faible puissance (5 W ou moins).',
    'QRQ': 'Transmettez plus vite.',
    'QRS': 'Transmettez plus lentement.',
    'QRT': 'Cessez d’émettre / Je cesse le trafic.',
    'QRU': 'Avez-vous quelque chose pour moi ? / Je n’ai rien pour vous.',
    'QRV': 'Êtes-vous prêt ? / Je suis prêt.',
    'QRX': 'Attendez ; je vous rappellerai à (heure).',
    'QRZ': 'Qui m’appelle ?',
    'QSB': 'Votre signal subit du fading (évanouissement).',
    'QSL': 'Pouvez-vous accuser réception ? / J’accuse réception.',
    'QSO': 'Un contact ; je peux communiquer avec (station).',
    'QSY': 'Passez sur une autre fréquence.',
    'QTH': 'Quelle est votre position ? / Ma position est (lieu).',
    'QRA': 'Le nom de ma station est (indicatif).',
    'QRG': 'Votre fréquence exacte est (kHz).',
    'QRH': 'Votre fréquence varie.',
    'QRI': 'La tonalité de votre émission est (bonne / variable / mauvaise).',
    'QRK': 'L’intelligibilité de votre signal est (1 à 5).',
    'QSA': 'La force de votre signal est (1 à 5).',
    'QSK': 'Je vous entends entre mes signaux ; vous pouvez m’interrompre.',
    'QSP': 'Pouvez-vous relayer à (station) ? / Je relaierai.',
    'QST': 'Appel général à toutes les stations amateurs.',
    'QSV': 'Transmettez une série de V pour le réglage.',
    'QSZ': 'Transmettez chaque mot ou groupe deux fois.',
    'QTC': 'J’ai (nombre) messages pour vous.',
    'QTR': 'Quelle est l’heure exacte ? / L’heure exacte est (UTC).',
  },
  abbreviations: <String, String>{
    'CQ': 'Appel à toutes les stations.',
    'DE': 'De (précède l’indicatif de l’émetteur).',
    'K': 'À vous, toute station.',
    'KN': 'À vous, seulement la station appelée.',
    '73': 'Meilleures amitiés (salutations).',
    '88': 'Affectueusement (bises).',
    'TU': 'Merci.',
    'AGN': 'De nouveau.',
    'ANT': 'Antenne.',
    'BK': 'Break ; à vous (passage rapide).',
    'BTU': 'Retour à vous.',
    'CUL': 'À plus tard.',
    'ES': 'Et.',
    'FB': 'Très bien, excellent (fine business).',
    'GA': 'Bon après-midi.',
    'GE': 'Bonsoir.',
    'GM': 'Bonjour (le matin).',
    'HR': 'Ici.',
    'HW': 'Comment me recevez-vous ?',
    'NR': 'Numéro.',
    'OM': 'Old man (tout opérateur masculin).',
    'PSE': 'S’il vous plaît.',
    'PWR': 'Puissance.',
    'R': 'Reçu / bien compris.',
    'RIG': 'Équipement de la station.',
    'RST': 'Report : lisibilité, force, tonalité.',
    'SRI': 'Désolé.',
    'TNX': 'Merci.',
    'UR': 'Votre / vous êtes.',
    'WX': 'Météo.',
    'XYL': 'Épouse (ex-young lady).',
    'YL': 'Young lady (opératrice).',
    'ABT': 'Environ / à propos de.',
    'ADR': 'Adresse.',
    'B4': 'Avant.',
    'C': 'Oui / correct.',
    'CFM': 'Je confirme.',
    'CPI': 'Copier (recevoir).',
    'CUD': 'Pourrait.',
    'DX': 'Station lointaine.',
    'GB': 'Au revoir.',
    'GN': 'Bonne nuit.',
    'GND': 'Terre (masse).',
    'GUD': 'Bon.',
    'HI': 'Rire.',
    'HPE': 'J’espère.',
    'NW': 'Maintenant.',
    'OP': 'Opérateur.',
    'RPT': 'Répétez.',
    'SIG': 'Signal.',
    'TKS': 'Merci.',
    'TMW': 'Demain.',
    'VY': 'Très.',
    'WKD': 'Contacté (worked).',
    'WUD': 'Auxiliaire anglais du conditionnel (would).',
    '55': 'Bonne chance.',
  },
  prosigns: <String, String>{
    'AR': 'Fin de message.',
    'SK': 'Fin de contact.',
    'BT': 'Séparation / nouveau paragraphe.',
    'KN': 'À vous, seulement la station appelée.',
    'AS': 'Attendez / restez à l’écoute.',
    'SN': 'Compris.',
    'SOS': 'Détresse.',
    'CT': 'Début de transmission (attention).',
    'HH': 'Erreur ; le dernier mot va être répété.',
  },
  punctuation: <String, String>{
    '.': 'Point',
    ',': 'Virgule',
    '?': 'Point d’interrogation',
    '\'': 'Apostrophe',
    '!': 'Point d’exclamation',
    '/': 'Barre oblique (barre de fraction)',
    '(': 'Parenthèse ouvrante',
    ')': 'Parenthèse fermante',
    '&': 'Esperluette (attendez)',
    ':': 'Deux-points',
    ';': 'Point-virgule',
    '=': 'Signe égal (séparation, BT)',
    '+': 'Signe plus (fin de message, AR)',
    '-': 'Trait d’union / moins',
    '_': 'Tiret bas',
    '"': 'Guillemets',
    '\$': 'Signe dollar',
    '@': 'Arobase',
  },
  digitPhrases: <String, String>{
    '1': 'un ti, puis quatre ta',
    '2': 'deux ti, puis trois ta',
    '3': 'trois ti, puis deux ta',
    '4': 'quatre ti, puis un ta',
    '5': 'cinq ti',
    '6': 'un ta, puis quatre ti',
    '7': 'deux ta, puis trois ti',
    '8': 'trois ta, puis deux ti',
    '9': 'quatre ta, puis un ti',
    '0': 'cinq ta',
  },
  phraseNote:
      ' (moyen mnémotechnique anglais ; les syllabes accentuées '
      'sont des ta)',
  rhythm: ReferenceRhythm(dit: 'ti', finalDit: 'ti', dah: 'TA', joiner: '-'),
);
