// Reference content in German. Rows and display order follow the English
// file; see reference_text.dart.
import 'reference_text.dart';

/// German reference content.
const ReferenceText referenceTextDe = ReferenceText(
  qCodes: <String, String>{
    'QRL': 'Ist die Frequenz belegt? / Die Frequenz ist belegt.',
    'QRM': 'Störungen durch andere Stationen (künstliche Störungen).',
    'QRN': 'Atmosphärische Störungen (Rauschen).',
    'QRO': 'Leistung erhöhen / hohe Leistung.',
    'QRP': 'Leistung verringern / kleine Leistung (5 W oder weniger).',
    'QRQ': 'Schneller geben.',
    'QRS': 'Langsamer geben.',
    'QRT': 'Sendung einstellen / Ich stelle den Betrieb ein.',
    'QRU': 'Hast du etwas für mich? / Ich habe nichts für dich.',
    'QRV': 'Bist du bereit? / Ich bin bereit.',
    'QRX': 'Bitte warten; ich rufe dich wieder um (Uhrzeit).',
    'QRZ': 'Wer ruft mich?',
    'QSB': 'Dein Signal schwankt (Fading).',
    'QSL': 'Kannst du den Empfang bestätigen? / Ich bestätige den Empfang.',
    'QSO': 'Eine Funkverbindung; ich kann mit (Station) verkehren.',
    'QSY': 'Auf eine andere Frequenz wechseln.',
    'QTH': 'Wo ist dein Standort? / Mein Standort ist (Ort).',
    'QRA': 'Der Name meiner Station ist (Rufzeichen).',
    'QRG': 'Deine genaue Frequenz ist (kHz).',
    'QRH': 'Deine Frequenz schwankt.',
    'QRI': 'Der Ton deiner Aussendung ist (gut / veränderlich / schlecht).',
    'QRK': 'Die Lesbarkeit deines Signals ist (1 bis 5).',
    'QSA': 'Die Stärke deines Signals ist (1 bis 5).',
    'QSK': 'Ich höre dich zwischen meinen Zeichen; du kannst unterbrechen.',
    'QSP': 'Kannst du an (Station) weiterleiten? / Ich leite weiter.',
    'QST': 'Allgemeiner Anruf an alle Amateurfunkstationen.',
    'QSV': 'Eine Reihe Vs zum Abstimmen geben.',
    'QSZ': 'Jedes Wort oder jede Gruppe zweimal geben.',
    'QTC': 'Ich habe (Anzahl) Nachrichten für dich.',
    'QTR': 'Wie spät ist es genau? / Die genaue Uhrzeit ist (UTC).',
  },
  abbreviations: <String, String>{
    'CQ': 'Allgemeiner Anruf an alle Stationen.',
    'DE': 'Von (vor dem Rufzeichen des Absenders).',
    'K': 'Bitte kommen, jede Station.',
    'KN': 'Bitte kommen, nur die gerufene Station.',
    '73': 'Viele Grüße.',
    '88': 'Liebe und Küsse.',
    'TU': 'Danke.',
    'AGN': 'Nochmals.',
    'ANT': 'Antenne.',
    'BK': 'Unterbrechung; zurück zu dir (schneller Wechsel).',
    'BTU': 'Zurück zu dir.',
    'CUL': 'Bis später.',
    'ES': 'Und.',
    'FB': 'Prima, ausgezeichnet (fine business).',
    'GA': 'Guten Tag (Nachmittag).',
    'GE': 'Guten Abend.',
    'GM': 'Guten Morgen.',
    'HR': 'Hier.',
    'HW': 'Wie hörst du mich?',
    'NR': 'Nummer.',
    'OM': 'Old Man (jeder männliche Funker).',
    'PSE': 'Bitte.',
    'PWR': 'Leistung.',
    'R': 'Verstanden / erhalten.',
    'RIG': 'Stationsausrüstung.',
    'RST': 'Rapport: Lesbarkeit, Stärke, Ton.',
    'SRI': 'Entschuldigung.',
    'TNX': 'Danke.',
    'UR': 'Dein / du bist.',
    'WX': 'Wetter.',
    'XYL': 'Ehefrau (ex-young lady).',
    'YL': 'Young Lady (Funkerin).',
    'ABT': 'Ungefähr / über.',
    'ADR': 'Adresse.',
    'B4': 'Vorher.',
    'C': 'Ja / richtig.',
    'CFM': 'Bestätige.',
    'CPI': 'Aufnehmen, mitschreiben.',
    'CUD': 'Könnte.',
    'DX': 'Weit entfernte Station.',
    'GB': 'Auf Wiederhören.',
    'GN': 'Gute Nacht.',
    'GND': 'Erde (Masse).',
    'GUD': 'Gut.',
    'HI': 'Lachen.',
    'HPE': 'Hoffe.',
    'NW': 'Jetzt.',
    'OP': 'Funker (Operator).',
    'RPT': 'Wiederholen.',
    'SIG': 'Signal.',
    'TKS': 'Danke.',
    'TMW': 'Morgen.',
    'VY': 'Sehr.',
    'WKD': 'Gearbeitet (Verbindung gehabt).',
    'WUD': 'Würde.',
    '55': 'Viel Erfolg.',
  },
  prosigns: <String, String>{
    'AR': 'Ende der Nachricht.',
    'SK': 'Ende der Verbindung.',
    'BT': 'Trennung / neuer Absatz.',
    'KN': 'Bitte kommen, nur die gerufene Station.',
    'AS': 'Warten / bitte warten.',
    'SN': 'Verstanden.',
    'SOS': 'Notruf.',
    'CT': 'Beginn der Sendung (Spruchanfang).',
    'HH': 'Irrung; das letzte Wort wird wiederholt.',
  },
  punctuation: <String, String>{
    '.': 'Punkt',
    ',': 'Komma',
    '?': 'Fragezeichen',
    '\'': 'Apostroph',
    '!': 'Ausrufezeichen',
    '/': 'Schrägstrich (Bruchstrich)',
    '(': 'Klammer auf',
    ')': 'Klammer zu',
    '&': 'Und-Zeichen (warten)',
    ':': 'Doppelpunkt',
    ';': 'Semikolon',
    '=': 'Gleichheitszeichen (Trennung, BT)',
    '+': 'Pluszeichen (Ende der Nachricht, AR)',
    '-': 'Bindestrich / Minus',
    '_': 'Unterstrich',
    '"': 'Anführungszeichen',
    '\$': 'Dollarzeichen',
    '@': 'At-Zeichen (Klammeraffe)',
  },
  digitPhrases: <String, String>{
    '1': 'ein Punkt, dann vier Striche',
    '2': 'zwei Punkte, dann drei Striche',
    '3': 'drei Punkte, dann zwei Striche',
    '4': 'vier Punkte, dann ein Strich',
    '5': 'fünf Punkte',
    '6': 'ein Strich, dann vier Punkte',
    '7': 'zwei Striche, dann drei Punkte',
    '8': 'drei Striche, dann zwei Punkte',
    '9': 'vier Striche, dann ein Punkt',
    '0': 'fünf Striche',
  },
  phraseNote: ' (englische Merkhilfe; betonte Silben sind Striche)',
);
