/// English, Simplified Chinese and Traditional Chinese lesson content.
const Map<String, (String, String, String)> wordMeaningsPart3 = {
  'REASON': ('an explanation; think logically', '原因；推理', '原因；推理'),
  'GIRL': ('a female child or young person', '女孩', '女孩'),
  'GUY': ('a man; a person informally', '男人；家伙', '男人；傢伙'),
  'MOMENT': ('a brief period of time', '片刻', '片刻'),
  'AIR': ('the gas surrounding the earth', '空气', '空氣'),
  'TEACHER': ('a person who helps others learn', '教师', '教師'),
  'FORCE': ('strength; make someone do something', '力；迫使', '力；迫使'),
  'FOOT': ('the body part used for standing; a length unit', '脚；英尺', '腳；英尺'),
  'BOY': ('a male child or young person', '男孩', '男孩'),
  'AGE': ('how long someone has lived', '年龄', '年齡'),
  'PROCESS': ('a series of actions', '过程；处理', '過程；處理'),
  'MUSIC': ('organized sounds made for listening', '音乐', '音樂'),
  'MARKET': ('a place or system for buying and selling', '市场', '市場'),
  'SENSE': ('a way to perceive; meaning', '感觉；意义', '感覺；意義'),
  'NATION': ('a country and its people', '国家；民族', '國家；民族'),
  'PLAN': ('an intended course of action', '计划', '計畫'),
  'INTEREST': ('curiosity; money charged on a loan', '兴趣；利息', '興趣；利息'),
  'EFFECT': ('a result or influence', '效果；影响', '效果；影響'),
  'CLASS': ('a group of students; a category', '班级；类别', '班級；類別'),
  'CONTROL': ('direct or manage', '控制', '控制'),
  'CARE': ('attention; look after', '关心；照料', '關心；照料'),
  'FIELD': ('open land; a subject area', '田地；领域', '田地；領域'),
  'ROLE': ('a function or part played', '角色；作用', '角色；作用'),
  'EFFORT': ('work done to achieve something', '努力', '努力'),
  'RATE': ('a speed; a proportion', '速率；比率', '速率；比率'),
  'HEART': ('the organ that pumps blood', '心脏；内心', '心臟；內心'),
  'SHOW': ('make visible; a performance', '展示；表演', '展示；表演'),
  'LEADER': ('a person who directs a group', '领导者', '領導者'),
  'LIGHT': ('brightness; not heavy', '光；轻的', '光；輕的'),
  'VOICE': ('sound made when speaking', '声音；嗓音', '聲音；嗓音'),
  'WIFE': ('a married female partner', '妻子', '妻子'),
  'MIND': ('thoughts and awareness; object to', '头脑；介意', '頭腦；介意'),
  'PRICE': ('the amount paid for something', '价格', '價格'),
  'REPORT': ('an account of information; provide information', '报告', '報告'),
  'SON': ('a male child of a parent', '儿子', '兒子'),
  'VIEW': ('what can be seen; an opinion', '景色；观点', '景色；觀點'),
  'TOWN': ('a place smaller than a city', '城镇', '城鎮'),
  'ROAD': ('a route for vehicles', '道路', '道路'),
  'ARM': ('a limb between shoulder and hand', '手臂', '手臂'),
  'VALUE': ('worth; a numerical amount', '价值；数值', '價值；數值'),
  'ACTION': ('something done', '行动', '行動'),
  'MODEL': ('a representation; an example to follow', '模型；示范', '模型；示範'),
  'SEASON': ('one of the parts of a year', '季节', '季節'),
  'TAX': ('money paid to the government', '税', '稅'),
  'PLAYER': ('a person taking part in a game', '玩家；运动员', '玩家；運動員'),
  'RECORD': ('stored information; store information', '记录', '紀錄'),
  'PAPER': ('material for writing or printing', '纸；论文', '紙；論文'),
  'SPACE': ('an empty area; outer space', '空间；太空', '空間；太空'),
  'GROUND': ('the surface of the earth', '地面', '地面'),
  'FORM': ('a shape; a document to fill in', '形状；表格', '形狀；表格'),
  'EVENT': ('something that happens', '事件；活动', '事件；活動'),
  'MATTER': (
    'a subject; physical substance; be important',
    '事情；物质；要紧',
    '事情；物質；要緊',
  ),
  'CENTER': ('the middle point', '中心', '中心'),
  'COUPLE': ('two people or things; a pair', '两个；一对', '兩個；一對'),
  'SITE': ('a place where something is located', '地点；站点', '地點；站點'),
  'PROJECT': ('a planned piece of work', '项目', '專案'),
  'STAR': ('a bright object in the night sky', '星；明星', '星；明星'),
  'TABLE': ('furniture with a flat top; arranged data', '桌子；表格', '桌子；表格'),
  'NEED': ('require; a requirement', '需要', '需要'),
  'COURT': ('a legal tribunal; a sports area', '法院；球场', '法院；球場'),
  'OIL': ('a thick liquid; petroleum', '油；石油', '油；石油'),
  'COST': ('the amount needed to buy or do something', '费用；成本', '費用；成本'),
  'FIGURE': ('a number; a shape; work out', '数字；形状；弄清', '數字；形狀；弄清'),
  'STREET': ('a road in a town or city', '街道', '街道'),
  'IMAGE': ('a picture; a mental impression', '图像；形象', '影像；形象'),
  'PHONE': ('a telephone', '电话', '電話'),
  'DATA': ('facts or information', '数据', '資料'),
  'PICTURE': ('a visual representation', '图片；画', '圖片；畫'),
  'PRACTICE': ('repeated activity to improve a skill', '练习', '練習'),
  'PIECE': ('a part of something', '一块；一件', '一塊；一件'),
  'LAND': ('the solid surface of the earth; arrive on it', '陆地；降落', '陸地；降落'),
  'PRODUCT': ('something made or sold', '产品', '產品'),
  'DOCTOR': ('a person who treats illness', '医生', '醫生'),
  'WALL': ('a vertical side of a building', '墙', '牆'),
  'NEWS': ('information about recent events', '新闻；消息', '新聞；消息'),
  'TEST': ('an examination; check something', '测试；检验', '測試；檢驗'),
  'NORTH': ('the direction opposite south', '北', '北'),
  'SOUTH': ('the direction opposite north', '南', '南'),
  'EAST': ('the direction of sunrise', '东', '東'),
  'WEST': ('the direction of sunset', '西', '西'),
  'LOVE': ('strong affection', '爱', '愛'),
  'STEP': ('one movement of the foot; a stage', '一步；步骤', '一步；步驟'),
  'BABY': ('a very young child', '婴儿', '嬰兒'),
  'TYPE': ('a category; enter text', '类型；打字', '類型；打字'),
  'RADIO': ('wireless communication; a receiver', '无线电；收音机', '無線電；收音機'),
  'ANTENNA': ('a device that transmits or receives radio waves', '天线', '天線'),
  'SIGNAL': ('a sign; a transmitted radio waveform', '信号', '訊號'),
  'CODE': ('a system of symbols or instructions', '代码；编码', '代碼；編碼'),
  'KEY': ('a lock opener; a telegraph key', '钥匙；电键', '鑰匙；電鍵'),
  'SEND': ('cause something to go; transmit', '发送；发报', '傳送；發報'),
};
