/// English, Simplified Chinese and Traditional Chinese lesson content.
const Map<String, (String, String, String)> wordMeaningsPart1 = {
  'THE': ('indicates a specific person or thing', '这／那；特指的人或事物', '這／那；特指的人或事物'),
  'BE': ('exist or have a quality', '是；存在', '是；存在'),
  'TO': ('toward; marks an infinitive', '到；向；用于动词原形前', '到；向；用於動詞原形前'),
  'OF': ('belonging to; related to', '属于；关于', '屬於；關於'),
  'AND': ('joins words or ideas', '和；而且', '和；而且'),
  'A': ('one unspecified person or thing', '一个；某一个', '一個；某一個'),
  'IN': ('inside; within', '在……里面', '在……裡面'),
  'THAT': ('the person or thing over there', '那；那个', '那；那個'),
  'HAVE': ('own; possess', '有；拥有', '有；擁有'),
  'I': ('the person speaking', '我', '我'),
  'IT': ('a thing already mentioned', '它；这件事', '它；這件事'),
  'FOR': ('intended for; because of', '为了；给；因为', '為了；給；因為'),
  'NOT': ('makes a statement negative', '不；没有', '不；沒有'),
  'ON': ('on top of; in contact with', '在……上；接触', '在……上；接觸'),
  'WITH': ('together with; using', '和……一起；使用', '和……一起；使用'),
  'HE': ('a male person', '他', '他'),
  'AS': ('in the role of; equally', '作为；像……一样', '作為；像……一樣'),
  'YOU': ('the person being addressed', '你；你们', '你；你們'),
  'DO': ('perform an action', '做；用于疑问或否定', '做；用於疑問或否定'),
  'AT': ('a particular place or time', '在某处；在某时', '在某處；在某時'),
  'THIS': ('the person or thing nearby', '这；这个', '這；這個'),
  'BUT': ('introduces a contrast', '但是', '但是'),
  'HIS': ('belonging to him', '他的', '他的'),
  'BY': ('beside; by means of', '在旁边；通过', '在旁邊；透過'),
  'FROM': ('starting at; originating in', '从；来自', '從；來自'),
  'THEY': ('people or things already mentioned', '他们；她们；它们', '他們；她們；它們'),
  'WE': ('the speaker and others', '我们', '我們'),
  'SAY': ('speak words', '说', '說'),
  'HER': ('a female person; belonging to her', '她；她的', '她；她的'),
  'SHE': ('a female person', '她', '她'),
  'OR': ('presents an alternative', '或者', '或者'),
  'AN': (
    'one unspecified thing before a vowel sound',
    '一个；用于元音发音前',
    '一個；用於母音發音前',
  ),
  'WILL': ('marks a future action; willingness', '将会；愿意', '將會；願意'),
  'MY': ('belonging to me', '我的', '我的'),
  'ONE': ('the number 1; a single item', '一；一个', '一；一個'),
  'ALL': ('every one; the whole amount', '全部；所有', '全部；所有'),
  'WOULD': (
    'imagined action; polite request',
    '会；愿意（假设或礼貌表达）',
    '會；願意（假設或禮貌表達）',
  ),
  'THERE': ('in that place', '那里', '那裡'),
  'THEIR': ('belonging to them', '他们的；她们的；它们的', '他們的；她們的；它們的'),
  'WHAT': ('asks about a thing or action', '什么', '什麼'),
  'SO': ('therefore; to such a degree', '所以；如此', '所以；如此'),
  'UP': ('toward a higher place', '向上', '向上'),
  'OUT': ('away from the inside', '向外；在外面', '向外；在外面'),
  'IF': ('on the condition that', '如果', '如果'),
  'ABOUT': ('concerning; approximately', '关于；大约', '關於；大約'),
  'WHO': ('asks which person', '谁', '誰'),
  'GET': ('obtain; become', '得到；变得', '得到；變得'),
  'WHICH': ('asks for a choice', '哪一个', '哪一個'),
  'GO': ('move to another place', '去；走', '去；走'),
  'ME': ('the speaker as an object', '我（宾格）', '我（受格）'),
  'WHEN': ('at what time', '什么时候；当……时', '什麼時候；當……時'),
  'MAKE': ('create; cause', '制作；使', '製作；使'),
  'CAN': ('be able to; be allowed to', '能够；可以', '能夠；可以'),
  'LIKE': ('enjoy; similar to', '喜欢；像', '喜歡；像'),
  'TIME': ('a moment or duration', '时间；次数', '時間；次數'),
  'NO': ('a negative answer; none', '不；没有', '不；沒有'),
  'JUST': ('only; a moment ago', '仅仅；刚刚', '僅僅；剛剛'),
  'HIM': ('a male person as an object', '他（宾格）', '他（受格）'),
  'KNOW': ('have information; understand', '知道；了解', '知道；了解'),
  'TAKE': ('get hold of; bring along', '拿；带走', '拿；帶走'),
  'PEOPLE': ('human beings', '人；人们', '人；人們'),
  'INTO': ('toward the inside', '进入……里面', '進入……裡面'),
  'YEAR': ('a period of twelve months', '年', '年'),
  'YOUR': ('belonging to you', '你的；你们的', '你的；你們的'),
  'GOOD': ('of high quality; pleasant', '好的', '好的'),
  'SOME': ('an unspecified amount', '一些', '一些'),
  'COULD': ('was able to; a possibility', '能够；可能（过去或假设）', '能夠；可能（過去或假設）'),
  'THEM': (
    'those people or things as an object',
    '他们；她们；它们（宾格）',
    '他們；她們；它們（受格）',
  ),
  'SEE': ('notice with the eyes', '看见', '看見'),
  'OTHER': ('different; additional', '其他的', '其他的'),
  'THAN': ('introduces a comparison', '比（用于比较）', '比（用於比較）'),
  'THEN': ('at that time; afterward', '那时；然后', '那時；然後'),
  'NOW': ('at the present time', '现在', '現在'),
  'LOOK': ('direct the eyes; appearance', '看；外观', '看；外觀'),
  'ONLY': ('no more than; solely', '只有；仅仅', '只有；僅僅'),
  'COME': ('move toward the speaker', '来', '來'),
  'ITS': ('belonging to it', '它的', '它的'),
  'OVER': ('above; across; finished', '在上方；越过；结束', '在上方；越過；結束'),
  'THINK': ('form an idea or opinion', '想；认为', '想；認為'),
  'ALSO': ('in addition', '也；还', '也；還'),
  'BACK': ('the rear; return', '后面；返回', '後面；返回'),
  'AFTER': ('later than; following', '在……之后', '在……之後'),
  'USE': ('put something to work', '使用', '使用'),
  'TWO': ('the number 2', '二；两个', '二；兩個'),
  'HOW': ('in what way', '怎样；如何', '怎樣；如何'),
  'OUR': ('belonging to us', '我们的', '我們的'),
  'WORK': ('do a job; a task', '工作', '工作'),
  'FIRST': ('before all others', '第一；首先', '第一；首先'),
  'WELL': ('in a good way; healthy', '好地；健康的', '好地；健康的'),
  'WAY': ('a method; a path', '方法；道路', '方法；道路'),
};
