/// English, Simplified Chinese and Traditional Chinese lesson content.
const Map<String, (String, String, String)> wordMeaningsPart4 = {
  'COPY': ('duplicate; receive and write a radio message', '复制；抄收', '複製；抄收'),
  'FAST': ('moving or happening quickly', '快的', '快的'),
  'SLOW': ('moving or happening at low speed', '慢的', '慢的'),
  'RAIN': ('water falling from clouds', '雨', '雨'),
  'SUN': ('the star that lights the earth', '太阳', '太陽'),
  'WIND': ('moving air', '风', '風'),
  'SNOW': ('frozen flakes falling from clouds', '雪', '雪'),
  'COLD': ('at a low temperature', '冷的', '冷的'),
  'WARM': ('at a comfortably high temperature', '温暖的', '溫暖的'),
  'HOT': ('at a high temperature', '热的', '熱的'),
  'OLD': ('having existed for a long time', '老的；旧的', '老的；舊的'),
  'BIG': ('large in size', '大的', '大的'),
  'SMALL': ('little in size', '小的', '小的'),
  'LONG': ('extending far in distance or time', '长的', '長的'),
  'HIGH': ('far above the ground; large in amount', '高的', '高的'),
  'LOW': ('close to the ground; small in amount', '低的', '低的'),
  'OPEN': ('not closed; make accessible', '打开；开放的', '打開；開放的'),
  'CLOSE': ('shut; near', '关闭；近的', '關閉；近的'),
  'RUN': ('move quickly on foot; operate', '跑；运行', '跑；運作'),
  'WALK': ('move on foot at a normal pace', '走路', '走路'),
  'READ': ('understand written words', '阅读', '閱讀'),
  'WRITE': ('put words into written form', '写', '寫'),
  'HEAR': ('perceive a sound', '听见', '聽見'),
  'CALL': ('speak to get attention; contact by radio', '呼叫；打电话', '呼叫；打電話'),
  'TALK': ('speak with someone', '说话；交谈', '說話；交談'),
  'MEET': ('come together with someone', '见面；相遇', '見面；相遇'),
  'HELP': ('give assistance', '帮助', '幫助'),
  'KEEP': ('retain; continue', '保留；保持', '保留；保持'),
  'START': ('begin', '开始', '開始'),
  'STOP': ('end an action or movement', '停止', '停止'),
  'TURN': ('change direction; a chance to act', '转动；轮到的机会', '轉動；輪到的機會'),
  'MOVE': ('change position', '移动', '移動'),
  'LIVE': ('be alive; reside', '生活；居住', '生活；居住'),
  'PLAY': ('take part in a game; produce music', '玩；演奏', '玩；演奏'),
  'PAY': ('give money for something', '支付', '支付'),
  'BUY': ('obtain by paying', '买', '買'),
  'TRY': ('attempt', '尝试', '嘗試'),
  'ASK': ('request information or help', '问；请求', '問；請求'),
  'TELL': ('give information', '告诉', '告訴'),
  'FEEL': ('experience a sensation or emotion', '感觉', '感覺'),
  'LEAVE': ('go away; allow to remain', '离开；留下', '離開；留下'),
  'PUT': ('place in a position', '放', '放'),
  'MEAN': ('have a meaning; intend', '意思是；打算', '意思是；打算'),
  'LET': ('allow', '让；允许', '讓；允許'),
  'BEGIN': ('start', '开始', '開始'),
  'SEEM': ('appear to be', '似乎', '似乎'),
  'STAND': ('be upright on the feet', '站立', '站立'),
  'LOSE': ('no longer have; fail to win', '失去；输', '失去；輸'),
  'ADD': ('put together; increase', '添加；相加', '新增；相加'),
  'SIT': ('rest on a seat', '坐', '坐'),
  'WAIT': ('stay until something happens', '等待', '等待'),
  'CUT': ('divide with a sharp tool; shorten', '切；缩短', '切；縮短'),
  'EAT': ('take food into the body', '吃', '吃'),
  'DRINK': ('take liquid into the body; a beverage', '喝；饮料', '喝；飲料'),
  'ONCE': ('one time; formerly', '一次；曾经', '一次；曾經'),
  'MORE': ('a greater amount', '更多', '更多'),
  'VERY': ('to a high degree', '很；非常', '很；非常'),
  'STILL': ('continuing; without movement', '仍然；静止的', '仍然；靜止的'),
  'HERE': ('in this place', '这里', '這裡'),
  'MUCH': ('a large amount', '许多；很', '許多；很'),
  'NEVER': ('not at any time', '从不', '從不'),
  'AGAIN': ('one more time', '再次', '再次'),
  'OFF': ('away; not operating', '离开；关闭', '離開；關閉'),
  'DOWN': ('toward a lower place', '向下', '向下'),
  'WHERE': ('in what place', '哪里', '哪裡'),
  'WHY': ('for what reason', '为什么', '為什麼'),
  'EACH': ('every individual one', '每个', '每個'),
  'SAME': ('identical; unchanged', '相同的', '相同的'),
  'FEW': ('a small number', '少数；几个', '少數；幾個'),
  'MANY': ('a large number', '许多', '許多'),
  'LAST': ('final; most recent; continue', '最后；上一个；持续', '最後；上一個；持續'),
  'NEXT': ('immediately following', '下一个', '下一個'),
  'BEST': ('of the highest quality', '最好的', '最好的'),
  'FREE': ('without cost; not restricted', '免费的；自由的', '免費的；自由的'),
  'TRUE': ('correct; based on fact', '真的；正确的', '真的；正確的'),
  'REAL': ('actually existing', '真实的', '真實的'),
  'FULL': ('containing as much as possible', '满的；完整的', '滿的；完整的'),
  'LATE': ('after the expected time', '晚的；迟到的', '晚的；遲到的'),
  'EARLY': ('before the usual time', '早的', '早的'),
  'QUIET': ('making little noise', '安静的', '安靜的'),
  'ZERO': ('the number 0', '零', '零'),
  'QUICK': ('fast; taking little time', '快的；迅速的', '快的；迅速的'),
  'JUMP': ('push off the ground into the air', '跳', '跳'),
  'FOX': ('a wild animal with a pointed nose and bushy tail', '狐狸', '狐狸'),
  'LAZY': ('unwilling to make an effort', '懒惰的', '懶惰的'),
  'DOG': ('a common domestic animal', '狗', '狗'),
  'VEX': ('annoy or worry', '使烦恼', '使煩惱'),
  'JAZZ': ('a style of music with improvisation', '爵士乐', '爵士樂'),
  'ZONE': ('an area with a particular purpose', '区域', '區域'),
  'QUIZ': ('a short test of knowledge', '小测验', '小測驗'),
};
