/// English, Simplified Chinese and Traditional Chinese lesson content.
const Map<String, (String, String, String)> wordMeaningsPart2 = {
  'EVEN': ('emphasizes an unexpected case; level', '甚至；平的', '甚至；平的'),
  'NEW': ('recently made; not used before', '新的', '新的'),
  'WANT': ('wish to have or do', '想要', '想要'),
  'BECAUSE': ('for the reason that', '因为', '因為'),
  'ANY': ('one or some without restriction', '任何；一些', '任何；一些'),
  'THESE': ('more than one nearby thing', '这些', '這些'),
  'GIVE': ('hand over; provide', '给；提供', '給；提供'),
  'DAY': ('a period of twenty-four hours', '天；白天', '天；白天'),
  'MOST': ('the greatest amount; nearly all', '最多；大多数', '最多；大多數'),
  'US': ('the speaker and others as an object', '我们（宾格）', '我們（受格）'),
  'IS': ('present form of be for one person or thing', '是（单数现在式）', '是（單數現在式）'),
  'ARE': (
    'present form of be for you or a plural',
    '是（复数或 you 的现在式）',
    '是（複數或 you 的現在式）',
  ),
  'WAS': ('past form of be for a singular subject', '是（单数过去式）', '是（單數過去式）'),
  'WERE': (
    'past form of be for you or a plural',
    '是（复数或 you 的过去式）',
    '是（複數或 you 的過去式）',
  ),
  'BEEN': ('past participle of be', '曾是；曾在（be 的过去分词）', '曾是；曾在（be 的過去分詞）'),
  'HAS': (
    'present form of have for a singular subject',
    '有（第三人称单数）',
    '有（第三人稱單數）',
  ),
  'HAD': (
    'past form and past participle of have',
    '有（have 的过去式／过去分词）',
    '有（have 的過去式／過去分詞）',
  ),
  'DID': ('past form of do', '做（do 的过去式）', '做（do 的過去式）'),
  'SAID': (
    'past form and past participle of say',
    '说（say 的过去式／过去分词）',
    '說（say 的過去式／過去分詞）',
  ),
  'MAN': ('an adult male', '男人', '男人'),
  'WOMAN': ('an adult female', '女人', '女人'),
  'CHILD': ('a young person', '儿童；孩子', '兒童；孩子'),
  'WORLD': ('the earth and its people', '世界', '世界'),
  'LIFE': ('being alive; a lifetime', '生命；生活', '生命；生活'),
  'HAND': ('the part at the end of an arm', '手', '手'),
  'PART': ('a portion of a whole', '部分', '部分'),
  'PLACE': ('a location; put somewhere', '地方；放置', '地方；放置'),
  'CASE': ('a situation; a container', '情况；箱子', '情況；箱子'),
  'WEEK': ('a period of seven days', '星期；周', '星期；週'),
  'COMPANY': ('a business; being with others', '公司；陪伴', '公司；陪伴'),
  'SYSTEM': ('connected parts working together', '系统', '系統'),
  'PROGRAM': ('a planned set of actions; software', '程序；计划', '程式；計畫'),
  'QUESTION': ('something asked', '问题；提问', '問題；提問'),
  'NUMBER': ('a quantity or numerical label', '数字；号码', '數字；號碼'),
  'NIGHT': ('the dark part of a day', '夜晚', '夜晚'),
  'POINT': ('a particular place; a main idea', '点；要点', '點；要點'),
  'HOME': ('the place where one lives', '家', '家'),
  'WATER': ('the liquid used for drinking', '水', '水'),
  'ROOM': ('a space inside a building; available space', '房间；空间', '房間；空間'),
  'MOTHER': ('a female parent', '母亲', '母親'),
  'AREA': ('a region; the size of a surface', '地区；面积', '地區；面積'),
  'MONEY': ('what is used to pay for things', '钱', '錢'),
  'STORY': ('an account of events', '故事', '故事'),
  'FACT': ('something known to be true', '事实', '事實'),
  'MONTH': ('one of twelve parts of a year', '月；月份', '月；月份'),
  'LOT': ('a large amount; a piece of land', '许多；一块地', '許多；一塊地'),
  'RIGHT': (
    'correct; opposite of left; an entitlement',
    '正确；右边；权利',
    '正確；右邊；權利',
  ),
  'STUDY': ('learn; examine carefully', '学习；研究', '學習；研究'),
  'BOOK': ('a written or printed work', '书', '書'),
  'EYE': ('the organ used for seeing', '眼睛', '眼睛'),
  'JOB': ('paid work; a task', '工作；任务', '工作；任務'),
  'WORD': ('a unit of language', '单词；词', '單字；詞'),
  'BUSINESS': ('trade; a commercial organization', '商业；生意', '商業；生意'),
  'ISSUE': ('a subject to discuss; distribute', '议题；发出', '議題；發出'),
  'SIDE': ('one surface or edge; a viewpoint', '一边；一方', '一邊；一方'),
  'KIND': ('a type; caring toward others', '种类；友善的', '種類；友善的'),
  'HEAD': ('the top part of the body; a leader', '头；负责人', '頭；負責人'),
  'HOUSE': ('a building to live in', '房屋', '房屋'),
  'SERVICE': ('help or work provided for others', '服务', '服務'),
  'FRIEND': ('a person one likes and knows', '朋友', '朋友'),
  'FATHER': ('a male parent', '父亲', '父親'),
  'POWER': ('ability; energy; radio output power', '力量；电力；发射功率', '力量；電力；發射功率'),
  'HOUR': ('a period of sixty minutes', '小时', '小時'),
  'GAME': ('an activity played for enjoyment', '游戏；比赛', '遊戲；比賽'),
  'LINE': ('a long narrow mark; a row', '线；一行', '線；一行'),
  'END': ('the final part; finish', '结尾；结束', '結尾；結束'),
  'MEMBER': ('a person in a group', '成员', '成員'),
  'LAW': ('a rule made by authorities', '法律；规律', '法律；規律'),
  'CAR': ('a road vehicle', '汽车', '汽車'),
  'CITY': ('a large town', '城市', '城市'),
  'NAME': ('a word identifying someone or something', '名字；名称', '名字；名稱'),
  'TEAM': ('a group working together', '团队', '團隊'),
  'MINUTE': ('a period of sixty seconds', '分钟', '分鐘'),
  'IDEA': ('a thought or plan', '想法', '想法'),
  'KID': ('a child', '孩子', '孩子'),
  'BODY': ('the physical form of a person or animal', '身体', '身體'),
  'PARENT': ('a mother or father', '父亲或母亲', '父親或母親'),
  'FACE': ('the front of the head; confront', '脸；面对', '臉；面對'),
  'LEVEL': ('a position on a scale; flat', '等级；水平的', '等級；水平的'),
  'OFFICE': ('a place for administrative work', '办公室', '辦公室'),
  'DOOR': ('an entrance that opens and closes', '门', '門'),
  'HEALTH': ('the condition of the body and mind', '健康', '健康'),
  'PERSON': ('an individual human being', '人；个人', '人；個人'),
  'ART': ('creative work such as painting', '艺术', '藝術'),
  'WAR': ('armed conflict', '战争', '戰爭'),
  'HISTORY': ('events of the past', '历史', '歷史'),
  'PARTY': ('a social gathering; a political group', '聚会；政党', '聚會；政黨'),
  'RESULT': ('what happens because of an action', '结果', '結果'),
  'CHANGE': ('become different; alter', '改变；变化', '改變；變化'),
  'MORNING': ('the early part of a day', '早晨', '早晨'),
};
