import 'dart:async';
import 'dart:ui' show Size;

import 'package:flutter/foundation.dart';

import 'key_value_store.dart';

/// Whether [platform] is one of the three desktop targets the shell drives.
///
/// Web is never a desktop target: `window_manager` / `tray_manager` have no
/// web implementation, so every shell call must stay a no-op there.
bool isDesktopTarget(TargetPlatform platform) =>
    !kIsWeb &&
    (platform == TargetPlatform.macOS ||
        platform == TargetPlatform.windows ||
        platform == TargetPlatform.linux);

/// Asset paths of the tray icons generated by `tool/gen_tray_icons.dart`.
///
/// macOS gets a *template* image (black glyph + alpha, AppKit tints it for
/// the light/dark menu bar); Linux gets a PNG for the StatusNotifier /
/// AppIndicator host; Windows needs a multi-resolution `.ico` because the
/// tray loads it with `LoadImage(IMAGE_ICON)`, which rejects plain PNGs.
abstract final class TrayIconAssets {
  static const String macTemplate = 'assets/tray/tray_template_32.png';
  static const String linuxPng = 'assets/tray/tray_icon_32.png';
  static const String windowsIco = 'assets/tray/tray_icon.ico';

  /// The icon [platform] should load, or null when it has no tray.
  static String? forPlatform(TargetPlatform platform) => switch (platform) {
    TargetPlatform.macOS => macTemplate,
    TargetPlatform.linux => linuxPng,
    TargetPlatform.windows => windowsIco,
    _ => null,
  };
}

/// Everything the desktop shell needs from the orchestrator (`main.dart`).
///
/// The shell gates every plugin call on [effectivePlatform], which defaults to
/// [defaultTargetPlatform] and can be pinned in tests (or by the orchestrator)
/// through [platform]. On Android / iOS / web the whole shell is a no-op.
class DesktopShellConfig {
  const DesktopShellConfig({
    required this.store,
    this.appName = 'MorseCQ',
    this.platform,
    this.minimumSize = const Size(360, 640),
    this.defaultSize = const Size(1100, 760),
    this.closeToTray = true,
    this.soundEnabled = true,
    this.onToggleSound,
    this.onBeforeQuit,
    this.persistDebounce = const Duration(milliseconds: 500),
    this.log,
  });

  /// Backs window bounds / maximised state / close-to-tray persistence. The
  /// orchestrator wraps `shared_preferences` (or any other store) in it.
  final KeyValueStore store;

  /// Window title and tray tooltip base text.
  final String appName;

  /// Overrides [defaultTargetPlatform]; leave null in production.
  final TargetPlatform? platform;

  /// Phone-like portrait must still work on desktop (the layout is
  /// responsive), hence the small default.
  final Size minimumSize;

  /// Window size on first launch (clamped to the primary display).
  final Size defaultSize;

  /// Initial value of the close-to-tray setting when nothing is persisted.
  final bool closeToTray;

  /// Initial state of the tray's "Sound on/off" toggle.
  final bool soundEnabled;

  /// Placeholder hook for the tray's "Sound on/off" toggle; the sidetone
  /// owner wires it later.
  final FutureOr<void> Function(bool enabled)? onToggleSound;

  /// Runs before the process exits through the tray's Quit or a real close.
  /// Use it for account teardown; it is bounded by the caller, not by us.
  final FutureOr<void> Function()? onBeforeQuit;

  /// How long to wait after the last move/resize before persisting bounds.
  final Duration persistDebounce;

  /// Diagnostic sink (defaults to [debugPrint]); the shell is cosmetic and
  /// never throws to its caller.
  final void Function(String message)? log;

  /// [log] or [debugPrint].
  void Function(String message) get logger => log ?? debugPrint;

  TargetPlatform get effectivePlatform => platform ?? defaultTargetPlatform;

  bool get isDesktop => isDesktopTarget(effectivePlatform);

  bool get isMacOS => effectivePlatform == TargetPlatform.macOS;

  bool get isLinux => effectivePlatform == TargetPlatform.linux;
}
