import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../i18n/current_strings.dart';
import '../l10n/generated/s.dart';
import 'local_notifications_api.dart';
import 'notification_platform.dart';

/// Production [LocalNotificationsApi] on `flutter_local_notifications`
/// (22.x). The only file in the app that imports the plugin.
///
/// Per platform (see README.md in this directory for the full table):
/// - Android: notification channels created up front; grouping via
///   `groupKey` + inbox style; `POST_NOTIFICATIONS` requested lazily.
/// - iOS / macOS: UNUserNotificationCenter; permission requested lazily
///   (the init settings turn the automatic prompt off); banners are shown in
///   the foreground too, because the center posts only for conversations the
///   user is *not* looking at.
/// - Linux: D-Bus `org.freedesktop.Notifications` via the endorsed
///   `flutter_local_notifications_linux`; no permission, no grouping.
/// - Windows: WinRT toasts via the endorsed FFI package
///   `flutter_local_notifications_windows`; no permission, no grouping;
///   `cancel` is a no-op unless the app is packaged as MSIX (plugin README).
///
/// Language: [strings] (default `currentS()`) is read on every [show] for the
/// Android channel name/description and the Linux action label, so those
/// follow the app language. Android **creates** the channels once, in
/// [initialize]; the OS keeps the name/description of an existing channel
/// (`createIfNotExists`), so what Android Settings shows is the language of
/// the first launch until the channels are re-created (see README).
final class FlutterLocalNotificationsApi implements LocalNotificationsApi {
  FlutterLocalNotificationsApi({
    FlutterLocalNotificationsPlugin? plugin,
    NotificationPlatform? platform,
    this.androidIcon = defaultAndroidIcon,
    S Function()? strings,
  }) : _plugin = plugin ?? FlutterLocalNotificationsPlugin(),
       _platform = platform ?? NotificationPlatform.detect(),
       _strings = strings ?? currentS;

  /// The status-bar small icon: white "CQ" glyph on transparent, generated by
  /// `tool/gen_app_icons.dart` into `res/drawable-*/`. Android draws small
  /// icons from the alpha channel only, so the opaque launcher mipmap would
  /// show as a solid square. Referenced by name only, so
  /// `res/raw/keep.xml` pins it against release resource shrinking.
  static const String defaultAndroidIcon = '@drawable/ic_stat_morsecq';

  /// Display name Windows registers for the toast platform together with
  /// [windowsAppUserModelId]. A product name, never translated. The registry
  /// entry is keyed by the AUMID, so this display value may change (it is
  /// rewritten on every init) without duplicating or orphaning anything.
  static const String windowsAppName = 'MorseCQ';

  /// Windows registers the app with the toast platform under this
  /// AppUserModelID; unpackaged apps register it in the registry on first
  /// init. Must stay stable across versions or old toasts orphan.
  static const String windowsAppUserModelId = 'icu.agentx.morsecq';

  /// COM activator CLSID for Windows toast activation. Generated once
  /// (2026-09-30) and must never change for the same [windowsAppUserModelId].
  static const String windowsGuid = 'e98da184-450e-43c1-88ba-c2082fc8de1d';

  final FlutterLocalNotificationsPlugin _plugin;
  final NotificationPlatform _platform;
  final String androidIcon;
  final S Function() _strings;
  bool _initialized = false;
  bool _refreshPending = false;

  /// Whether the Linux notification server parses the body as markup
  /// (`body-markup` capability); only then must peer text be escaped.
  bool _linuxBodyMarkup = false;

  @override
  Future<bool> initialize({required ValueChanged<String> onTap}) async {
    if (_initialized) return true;
    if (!_platform.supportsOsNotifications) return false;
    try {
      const DarwinInitializationSettings darwin = DarwinInitializationSettings(
        // Permission is driven by requestPermission() so the prompt happens
        // when the app decides (not on first launch behind the splash).
        requestAlertPermission: false,
        requestBadgePermission: false,
        requestSoundPermission: false,
      );
      final InitializationSettings settings = InitializationSettings(
        android: AndroidInitializationSettings(androidIcon),
        iOS: darwin,
        macOS: darwin,
        linux: LinuxInitializationSettings(
          defaultActionName: _strings().notificationOpen,
        ),
        windows: const WindowsInitializationSettings(
          appName: windowsAppName,
          appUserModelId: windowsAppUserModelId,
          guid: windowsGuid,
        ),
      );
      final bool? ok = await _plugin.initialize(
        settings: settings,
        onDidReceiveNotificationResponse: (NotificationResponse response) {
          final String? payload = response.payload;
          if (payload != null && payload.isNotEmpty) onTap(payload);
        },
      );
      if (ok == false) return false;
      if (_platform == NotificationPlatform.linux) {
        _linuxBodyMarkup = await _linuxSupportsBodyMarkup();
      }
      if (_platform == NotificationPlatform.android) {
        // A language change that arrives while the channels are being
        // written sets _refreshPending; loop until a pass ran with the
        // latest strings.
        do {
          _refreshPending = false;
          await _createAndroidChannels();
        } while (_refreshPending);
      }
      _initialized = true;
      return true;
    } catch (error, stack) {
      _report('initialize', error, stack);
      return false;
    }
  }

  @override
  Future<String?> takeLaunchPayload() async {
    if (!_initialized) return null;
    try {
      final NotificationAppLaunchDetails? details = await _plugin
          .getNotificationAppLaunchDetails();
      if (details == null || !details.didNotificationLaunchApp) return null;
      final String? payload = details.notificationResponse?.payload;
      return (payload == null || payload.isEmpty) ? null : payload;
    } catch (error, stack) {
      _report('takeLaunchPayload', error, stack);
      return null;
    }
  }

  @override
  Future<bool> requestPermission() async {
    try {
      switch (_platform) {
        case NotificationPlatform.android:
          final AndroidFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                AndroidFlutterLocalNotificationsPlugin
              >();
          if (impl == null) return false;
          // No-op (null) below API 33, where notifications are on by default
          // unless the user turned them off in settings.
          final bool? granted = await impl.requestNotificationsPermission();
          return granted ?? (await impl.areNotificationsEnabled() ?? true);
        case NotificationPlatform.ios:
          final IOSFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                IOSFlutterLocalNotificationsPlugin
              >();
          return await impl?.requestPermissions(
                alert: true,
                badge: true,
                sound: true,
              ) ??
              false;
        case NotificationPlatform.macos:
          final MacOSFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                MacOSFlutterLocalNotificationsPlugin
              >();
          return await impl?.requestPermissions(
                alert: true,
                badge: true,
                sound: true,
              ) ??
              false;
        case NotificationPlatform.linux:
        case NotificationPlatform.windows:
          return true;
        case NotificationPlatform.unsupported:
          return false;
      }
    } catch (error, stack) {
      _report('requestPermission', error, stack);
      return false;
    }
  }

  @override
  Future<bool> isPermissionGranted() async {
    try {
      switch (_platform) {
        case NotificationPlatform.android:
          final AndroidFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                AndroidFlutterLocalNotificationsPlugin
              >();
          // POST_NOTIFICATIONS on 13+, the app-level switch below that.
          return await impl?.areNotificationsEnabled() ?? false;
        case NotificationPlatform.ios:
          final IOSFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                IOSFlutterLocalNotificationsPlugin
              >();
          return (await impl?.checkPermissions())?.isEnabled ?? false;
        case NotificationPlatform.macos:
          final MacOSFlutterLocalNotificationsPlugin? impl = _plugin
              .resolvePlatformSpecificImplementation<
                MacOSFlutterLocalNotificationsPlugin
              >();
          return (await impl?.checkPermissions())?.isEnabled ?? false;
        case NotificationPlatform.linux:
        case NotificationPlatform.windows:
          return true;
        case NotificationPlatform.unsupported:
          return false;
      }
    } catch (error, stack) {
      _report('isPermissionGranted', error, stack);
      return false;
    }
  }

  @override
  Future<void> show(NotificationRequest request) async {
    if (!_initialized) return;
    await _plugin.show(
      id: request.id,
      title: request.title,
      // Freedesktop servers that advertise `body-markup` parse the body as
      // markup; peer text must not inject links or formatting there.
      body: _linuxBodyMarkup ? escapeLinuxBodyMarkup(request.body) : request.body,
      payload: request.payload,
      notificationDetails: _details(request),
    );
  }

  Future<bool> _linuxSupportsBodyMarkup() async {
    try {
      final LinuxFlutterLocalNotificationsPlugin? linux = _plugin
          .resolvePlatformSpecificImplementation<
            LinuxFlutterLocalNotificationsPlugin
          >();
      final LinuxServerCapabilities? caps = await linux?.getCapabilities();
      // Unknown: escape. Visible entities beat injected links.
      return caps?.bodyMarkup ?? true;
    } catch (error, stack) {
      _report('getCapabilities', error, stack);
      return true;
    }
  }

  /// Escapes the characters the freedesktop body markup subset reacts to.
  @visibleForTesting
  static String escapeLinuxBodyMarkup(String body) => body
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');

  @override
  Future<void> cancel(int id) async {
    if (!_initialized) return;
    await _plugin.cancel(id: id);
  }

  @override
  Future<void> cancelAll() async {
    if (!_initialized) return;
    await _plugin.cancelAll();
  }

  @override
  Future<List<String>> activePayloads() async {
    if (!_initialized) return const <String>[];
    try {
      final List<ActiveNotification> active = await _plugin
          .getActiveNotifications();
      return [
        for (final ActiveNotification n in active)
          if (n.payload case final String payload when payload.isNotEmpty)
            payload,
      ];
    } catch (error, stack) {
      // Not supported here (e.g. Linux): nothing to report.
      _report('activePayloads', error, stack);
      return const <String>[];
    }
  }

  NotificationDetails _details(NotificationRequest request) {
    final S s = _strings();
    final bool grouped = request.lines.length > 1;
    final NotificationChannelKind channel = request.channel;
    final AndroidNotificationDetails android = AndroidNotificationDetails(
      channel.androidId,
      channel.displayName(s),
      channelDescription: channel.description(s),
      importance: Importance.high,
      priority: Priority.high,
      category: channel.androidCategory,
      // Explicit, not the platform default: on a secure lock screen only the
      // app name shows until the device is unlocked.
      visibility: NotificationVisibility.private,
      groupKey: request.groupKey,
      playSound: request.sound && !request.silentUpdate,
      enableVibration: request.sound && !request.silentUpdate,
      onlyAlertOnce: request.silentUpdate,
      silent: request.silentUpdate,
      number: grouped ? request.lines.length : null,
      styleInformation: grouped
          ? InboxStyleInformation(
              request.lines,
              contentTitle: request.title,
              summaryText: request.summary,
            )
          : null,
    );
    final DarwinNotificationDetails darwin = DarwinNotificationDetails(
      threadIdentifier: request.groupKey,
      presentAlert: !request.silentUpdate,
      presentBanner: !request.silentUpdate,
      presentList: true,
      presentBadge: true,
      presentSound: request.sound && !request.silentUpdate,
      interruptionLevel: request.silentUpdate
          ? InterruptionLevel.passive
          : null,
    );
    final LinuxNotificationDetails linux = LinuxNotificationDetails(
      category: channel == NotificationChannelKind.messages
          ? LinuxNotificationCategory.imReceived
          : LinuxNotificationCategory.im,
      suppressSound: !request.sound || request.silentUpdate,
      defaultActionName: s.notificationOpen,
    );
    final WindowsNotificationDetails windows = WindowsNotificationDetails(
      audio: request.sound && !request.silentUpdate
          ? null
          : WindowsNotificationAudio.silent(),
    );
    return NotificationDetails(
      android: android,
      iOS: darwin,
      macOS: darwin,
      linux: linux,
      windows: windows,
    );
  }

  @override
  Future<void> refreshStrings() async {
    if (_platform != NotificationPlatform.android) return;
    if (!_initialized) {
      // Remembered and applied at the end of initialize().
      _refreshPending = true;
      return;
    }
    try {
      await _createAndroidChannels();
    } catch (error, stack) {
      _report('refreshStrings', error, stack);
    }
  }

  Future<void> _createAndroidChannels() async {
    final AndroidFlutterLocalNotificationsPlugin? impl = _plugin
        .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin
        >();
    if (impl == null) return;
    final S s = _strings();
    for (final NotificationChannelKind kind in NotificationChannelKind.values) {
      // Re-creating an existing channel only updates name/description;
      // importance and sound are frozen by Android once the channel exists.
      // [refreshStrings] re-runs this on a language change so Settings shows
      // the current language, not the one of the first launch.
      await impl.createNotificationChannel(
        AndroidNotificationChannel(
          kind.androidId,
          kind.displayName(s),
          description: kind.description(s),
          importance: Importance.high,
        ),
      );
    }
  }

  static void _report(String what, Object error, StackTrace stack) {
    debugPrint('[FlutterLocalNotificationsApi] $what failed: $error\n$stack');
  }
}

/// Android channel metadata for each [NotificationChannelKind].
extension NotificationChannelKindAndroid on NotificationChannelKind {
  String get androidId => switch (this) {
    NotificationChannelKind.messages => 'morsecq_messages',
    NotificationChannelKind.friendRequests => 'morsecq_friend_requests',
    NotificationChannelKind.groupInvites => 'morsecq_group_invites',
  };

  /// Channel name as shown in Android Settings, in the language of [s].
  String displayName(S s) => switch (this) {
    NotificationChannelKind.messages => s.notificationChannelMessages,
    NotificationChannelKind.friendRequests =>
      s.notificationChannelFriendRequests,
    NotificationChannelKind.groupInvites => s.notificationChannelGroupInvites,
  };

  String description(S s) => switch (this) {
    NotificationChannelKind.messages =>
      s.notificationChannelMessagesDescription,
    NotificationChannelKind.friendRequests =>
      s.notificationChannelFriendRequestsDescription,
    NotificationChannelKind.groupInvites =>
      s.notificationChannelGroupInvitesDescription,
  };

  AndroidNotificationCategory get androidCategory => switch (this) {
    NotificationChannelKind.messages => AndroidNotificationCategory.message,
    NotificationChannelKind.friendRequests ||
    NotificationChannelKind.groupInvites => AndroidNotificationCategory.social,
  };
}
