#!/usr/bin/env bash
#
# build_ios_store.sh — the iOS App Store build: MorseCQ as a purely offline
# Morse trainer (no chat, no identity, no network; doc/release/APP_STORE.md).
#
#   tool/build_ios_store.sh [--no-codesign] [extra `flutter build ipa` args]
#
# 1. Writes the gitignored ios/Runner/Info-Store.plist (Info.plist with
#    ITSAppUsesNonExemptEncryption = NO) and ios/Flutter/Store.xcconfig, which
#    points MORSECQ_INFOPLIST (INFOPLIST_FILE) at it. Tracked files are not
#    touched.
# 2. Runs `pod install` with MORSECQ_CHAT=false so the Podfile leaves the
#    Tim2ToxFFI pod (c-toxcore + libsodium) out. MORSECQ_CHAT stays exported
#    for the whole build: a pod install Flutter decides to run keeps it out.
# 3. `flutter build ipa --release --dart-define=MORSECQ_CHAT=false`.
# 4. Verifies the archived app: no tim2tox_ffi.framework, no libsodium or
#    toxcore symbols in any Mach-O, the privacy manifest present and
#    ITSAppUsesNonExemptEncryption false; then the exported IPA if one exists.
# 5. Always (trap): removes the generated files and runs `pod install` again
#    without the variable, so the next chat build has Tim2ToxFFI back.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/apps/morsecq"
IOS_DIR="$APP_DIR/ios"
STORE_PLIST="$IOS_DIR/Runner/Info-Store.plist"
STORE_XCCONFIG="$IOS_DIR/Flutter/Store.xcconfig"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[ios-store]${NC} $*"; }
err()  { echo -e "${RED}[ios-store]${NC} $*" >&2; }

[[ "$OSTYPE" == darwin* ]] || { err "macOS only (needs Xcode)"; exit 1; }
for tool in flutter pod plutil xcrun unzip; do
  command -v "$tool" >/dev/null || { err "$tool not found"; exit 1; }
done

restore() {
  local rc=$?
  rm -f "$STORE_PLIST" "$STORE_XCCONFIG"
  info "restoring the chat build's pods"
  (cd "$IOS_DIR" && env -u MORSECQ_CHAT pod install >/dev/null) \
    || err "pod install (restore) failed — run it in apps/morsecq/ios before the next chat build"
  exit "$rc"
}
trap restore EXIT

info "deriving Info-Store.plist"
cp "$IOS_DIR/Runner/Info.plist" "$STORE_PLIST"
plutil -replace ITSAppUsesNonExemptEncryption -bool NO "$STORE_PLIST"
cat > "$STORE_XCCONFIG" <<XC
// Generated by tool/build_ios_store.sh; deleted when it exits.
MORSECQ_INFOPLIST = Runner/Info-Store.plist
XC

export MORSECQ_CHAT=false
info "pod install without Tim2ToxFFI"
(cd "$IOS_DIR" && pod install >/dev/null)
if grep -q 'Tim2ToxFFI' "$IOS_DIR/Podfile.lock"; then
  err "Podfile.lock still lists Tim2ToxFFI"; exit 1
fi

info "flutter build ipa (offline)"
(cd "$APP_DIR" && flutter build ipa --release --dart-define=MORSECQ_CHAT=false "$@")

# ── verification ─────────────────────────────────────────────────────────────
verify_app() {  # <Runner.app>
  local app="$1" ok=1 bin
  [[ -d "$app" ]] || { err "no app at $app"; return 1; }
  if [[ -e "$app/Frameworks/tim2tox_ffi.framework" ]]; then
    err "tim2tox_ffi.framework is bundled"; ok=0
  fi
  while IFS= read -r bin; do
    # Count instead of `grep -q`: an early grep exit would SIGPIPE nm and,
    # under pipefail, turn a hit into a silent pass.
    local hits
    hits="$( (xcrun nm -gU "$bin" 2>/dev/null || true) | grep -Ec '_(crypto_box|crypto_secretbox|sodium_init|tox_new|tox_self_get_address)\b' || true)"
    if [[ "${hits:-0}" -gt 0 ]]; then
      err "Tox / libsodium symbols in ${bin#"$app"/}"; ok=0
    fi
  done < <(find "$app" -type f -perm -u+x)
  [[ -f "$app/PrivacyInfo.xcprivacy" ]] || { err "PrivacyInfo.xcprivacy missing"; ok=0; }
  local enc
  enc="$(plutil -extract ITSAppUsesNonExemptEncryption raw -o - "$app/Info.plist" 2>/dev/null || echo missing)"
  [[ "$enc" == "false" ]] || { err "ITSAppUsesNonExemptEncryption is '$enc', expected false"; ok=0; }
  [[ "$ok" == "1" ]] && info "verified $(basename "$(dirname "$(dirname "$app")")")/…/$(basename "$app")"
  [[ "$ok" == "1" ]]
}

ARCHIVE_APP="$APP_DIR/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
verify_app "$ARCHIVE_APP"

shopt -s nullglob
ipas=("$APP_DIR"/build/ios/ipa/*.ipa)
if [[ ${#ipas[@]} -gt 0 ]]; then
  tmp="$(mktemp -d)"
  unzip -q "${ipas[0]}" -d "$tmp"
  apps=("$tmp"/Payload/*.app)
  verify_app "${apps[0]}"
  rm -rf "$tmp"
  info "IPA ready: ${ipas[0]}"
else
  info "no IPA exported (unsigned build); the archive is verified"
fi
