// Generates the Chinese telegraph code tables for packages/morse_core from
// the Unicode Unihan database.
//
//   curl -sSLO https://www.unicode.org/Public/UNIDATA/Unihan.zip
//   unzip -o Unihan.zip Unihan_OtherMappings.txt -d /tmp/unihan
//   dart run tool/gen_telegraph_table.dart /tmp/unihan/Unihan_OtherMappings.txt
//
// Reads the `kMainlandTelegraph` (1983 mainland codebook) and
// `kTaiwanTelegraph` (Taiwan / Hong Kong codebook) fields and writes
// packages/morse_core/lib/src/telegraph/telegraph_table.g.dart: one
// `Map<String, int>` (character → 4-digit code) per codebook, sorted by code
// point so the output is stable across runs. Several characters can share a
// code (simplified / traditional pairs); the code → characters direction is
// derived at runtime.
//
// Data licence: Unicode License v3; the full copyright and permission
// notice lives in packages/morse_core/THIRD_PARTY_NOTICES.md and the
// generated file carries the Unihan version it was made from.

import 'dart:io';

const String _out = 'packages/morse_core/lib/src/telegraph/telegraph_table.g.dart';

void main(List<String> args) {
  if (!File('pubspec.yaml').existsSync() || !Directory('packages').existsSync()) {
    stderr.writeln('[gen_telegraph_table] run from the repository root');
    exit(1);
  }
  if (args.length != 1) {
    stderr.writeln(
      'usage: dart run tool/gen_telegraph_table.dart <Unihan_OtherMappings.txt>',
    );
    exit(2);
  }
  final lines = File(args.first).readAsLinesSync();
  var version = 'unknown';
  final mainland = <int, int>{};
  final taiwan = <int, int>{};
  // A character listed with several codes (`1057 7775`): the first is the
  // code we encode to, the rest still decode to the character.
  final mainlandAliases = <int, int>{};
  final taiwanAliases = <int, int>{};
  for (final line in lines) {
    if (line.startsWith('#')) {
      final m = RegExp(r'Unicode Version (\S+)').firstMatch(line);
      if (m != null) version = m.group(1)!;
      continue;
    }
    final parts = line.split('\t');
    if (parts.length != 3) continue;
    final (target, aliases) = switch (parts[1]) {
      'kMainlandTelegraph' => (mainland, mainlandAliases),
      'kTaiwanTelegraph' => (taiwan, taiwanAliases),
      _ => (null, null),
    };
    if (target == null || aliases == null) continue;
    final cp = int.parse(parts[0].substring(2), radix: 16);
    final codes = parts[2].trim().split(RegExp(r'\s+')).map(int.parse);
    var first = true;
    for (final code in codes) {
      if (code < 0 || code > 9999) {
        stderr.writeln('[gen_telegraph_table] odd code $code for ${parts[0]}');
        continue;
      }
      if (first) {
        target[cp] = code;
        first = false;
      } else {
        aliases[code] = cp;
      }
    }
  }
  if (mainland.isEmpty || taiwan.isEmpty) {
    stderr.writeln('[gen_telegraph_table] no telegraph fields found');
    exit(1);
  }

  final sb = StringBuffer()
    ..writeln('// GENERATED by tool/gen_telegraph_table.dart from the Unicode Unihan')
    ..writeln('// database (Unicode $version, fields kMainlandTelegraph /')
    ..writeln('// kTaiwanTelegraph). Do not edit; re-run the tool instead.')
    ..writeln('// Data: Copyright © 1991-2026 Unicode, Inc., used under the Unicode')
    ..writeln('// License v3; full copyright and permission notice in')
    ..writeln('// packages/morse_core/THIRD_PARTY_NOTICES.md (https://www.unicode.org/license.txt).')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// Unihan version the tables were generated from.')
    ..writeln("const String telegraphTableUnicodeVersion = '$version';")
    ..writeln();
  _writeMap(sb, 'mainlandTelegraphCodes', mainland,
      'Character → code, mainland (1983) codebook. ${mainland.length} entries.');
  _writeMap(sb, 'taiwanTelegraphCodes', taiwan,
      'Character → code, Taiwan / Hong Kong codebook. ${taiwan.length} entries.');
  _writeAliases(sb, 'mainlandTelegraphAliases', mainlandAliases,
      'Extra codes → character, mainland codebook (a character listed with '
      'several codes; encoding uses the first). ${mainlandAliases.length} entries.');
  _writeAliases(sb, 'taiwanTelegraphAliases', taiwanAliases,
      'Extra codes → character, Taiwan / Hong Kong codebook. '
      '${taiwanAliases.length} entries.');
  File(_out)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(sb.toString(), flush: true);
  stdout.writeln(
    '[gen_telegraph_table] Unicode $version: mainland ${mainland.length}, '
    'taiwan ${taiwan.length} → $_out',
  );
}

void _writeAliases(
    StringBuffer sb, String name, Map<int, int> map, String doc) {
  final codes = map.keys.toList()..sort();
  sb
    ..writeln('/// $doc')
    ..writeln('const Map<int, String> $name = {');
  for (final code in codes) {
    sb.writeln("  $code: '\\u{${map[code]!.toRadixString(16)}}',");
  }
  sb
    ..writeln('};')
    ..writeln();
}

void _writeMap(StringBuffer sb, String name, Map<int, int> map, String doc) {
  final keys = map.keys.toList()..sort();
  sb
    ..writeln('/// $doc')
    ..writeln('const Map<String, int> $name = {');
  final line = StringBuffer('  ');
  for (final cp in keys) {
    final entry = "'\\u{${cp.toRadixString(16)}}': ${map[cp]}, ";
    if (line.length + entry.length > 78) {
      sb.writeln(line.toString().trimRight());
      line
        ..clear()
        ..write('  ');
    }
    line.write(entry);
  }
  if (line.length > 2) sb.writeln(line.toString().trimRight());
  sb
    ..writeln('};')
    ..writeln();
}
